apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wikidata-zazuko-com

commonLabels:
  app.kubernetes.io/name: trifid
  app.kubernetes.io/instance: wikidata.zazuko.com

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
