apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  environment: production

# JSON patch that replace the ingress hostname to `wikidata.kube.zazuko.com`.
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: trifid
  path: ingress_patch.yaml

namespace: wikidata-zazuko-com
