apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO(sandhose): use the real reference once zazuko/trifid#52 is merged
bases:
- git::https://github.com/sandhose/trifid//k8s?ref=kustomize

resources:
- ingress.yaml

namePrefix: wikidata-

commonLabels:
  instance: wikidata

# JSON patch to add the pull secret to the deployment
# In the cluster there should be a `gitlab-registry` secret in the same namespace.
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: trifid
  path: pull_secret.yaml

images:
- name: docker.io/zazuko/trifid
  newName: registry.zazuko.com/docker/wikidata.zazuko.com
